<?php

namespace Database\Seeders;

use App\Models\CursoPorEixo;
use Database\Seeders\Concerns\UsaCicloPortfolio;
use Illuminate\Database\Seeder;

class CursoPorEixoSeeder extends Seeder
{
    use UsaCicloPortfolio;
    public function run(): void
    {
        $registros = [
            [
                'curso' => 'Açougueiro',
                'eixo' => 'Gastronomia',
                'unidade' => 'Faculdade de Tecnologia e Inovação Senac-DF — Campus 712/912 Norte',
                'ano' => '2025',
                'ch' => '160',
                'turmas' => '1',
                'codigo' => '2025.12.92',
                'alunos' => '11',
                'instrutores' => 'Hermesson Felipe Santos Da Silva',
                'status' => 'Ativo',
                'is_novo' => false,
                'observacao' => null,
            ],
            [
                'curso' => 'Práticas Operacionais em Cozinha',
                'eixo' => 'Gastronomia',
                'unidade' => 'Faculdade de Tecnologia e Inovação Senac-DF — Campus 913 Sul',
                'ano' => '2025',
                'ch' => '360',
                'turmas' => '1',
                'codigo' => '2025.12.70 - Não executada',
                'alunos' => '0',
                'instrutores' => 'Ronipeterson Borges Rosa',
                'status' => 'Inativo',
                'is_novo' => false,
                'observacao' => null,
            ],
            [
                'curso' => 'Barista',
                'eixo' => 'Bebidas',
                'unidade' => 'Taguatinga',
                'ano' => '2025',
                'ch' => '160',
                'turmas' => '1',
                'codigo' => '2025.26.18',
                'alunos' => '16',
                'instrutores' => 'Barbara Cristina Soares Carvalho',
                'status' => 'Ativo',
                'is_novo' => false,
                'observacao' => null,
            ],
            [
                'curso' => 'Sommelier de Cachaça',
                'eixo' => 'Bebidas',
                'unidade' => 'Gama',
                'ano' => '2025',
                'ch' => '100',
                'turmas' => '1',
                'codigo' => '2025.26.22',
                'alunos' => '15',
                'instrutores' => 'Barbara Cristina Soares Carvalho',
                'status' => 'Ativo',
                'is_novo' => false,
                'observacao' => null,
            ],
            [
                'curso' => 'Padaria Artesanal',
                'eixo' => 'Panificação',
                'unidade' => 'Ceilândia',
                'ano' => '2025',
                'ch' => '8',
                'turmas' => '6',
                'codigo' => 'Parceiro',
                'alunos' => '24',
                'instrutores' => 'Iracema',
                'status' => 'Ativo',
                'is_novo' => false,
                'observacao' => null,
            ],
            [
                'curso' => 'Cake design - Aperfeiçoamento',
                'eixo' => 'Confeitaria',
                'unidade' => 'Sobradinho',
                'ano' => '2025',
                'ch' => '40',
                'turmas' => '1',
                'codigo' => '2025.12.80',
                'alunos' => '7',
                'instrutores' => 'Maria Claudia Nascimento',
                'status' => 'Ativo',
                'is_novo' => false,
                'observacao' => null,
            ],
            [
                'curso' => 'Recepcionista em Meios de Hospedagem',
                'eixo' => 'Hospitalidade',
                'unidade' => 'Faculdade de Tecnologia e Inovação Senac-DF — Campus Taguatinga',
                'ano' => '2025',
                'ch' => '160',
                'turmas' => '1',
                'codigo' => '2025.12.75',
                'alunos' => '10',
                'instrutores' => 'Yuri Guedes Bayma Almeida',
                'status' => 'Ativo',
                'is_novo' => false,
                'observacao' => null,
            ],
            [
                'curso' => 'Agente de Viagens',
                'eixo' => 'Turismo',
                'unidade' => 'Ceilândia',
                'ano' => '2025',
                'ch' => '160',
                'turmas' => '1',
                'codigo' => '2025.12.88',
                'alunos' => '12',
                'instrutores' => 'Ana Paula Mendes',
                'status' => 'Ativo',
                'is_novo' => false,
                'observacao' => null,
            ],
            [
                'curso' => 'Administrador de Redes',
                'eixo' => 'Tecnologia da Informação - Suporte',
                'unidade' => 'São Sebastião',
                'ano' => '2025',
                'ch' => '200',
                'turmas' => '1',
                'codigo' => '2025.07.120',
                'alunos' => '15',
                'instrutores' => 'Moises Mendes de Andrade',
                'status' => 'Ativo',
                'is_novo' => false,
                'observacao' => null,
            ],
            [
                'curso' => 'ChatGPT na Prática',
                'eixo' => 'Tecnologia da Informação - Inovação',
                'unidade' => 'Faculdade de Tecnologia e Inovação Senac-DF — Campus 913 Sul',
                'ano' => '2025',
                'ch' => '36',
                'turmas' => '3',
                'codigo' => '2025.08.11',
                'alunos' => '12',
                'instrutores' => 'Juliana Mendes De Brito',
                'status' => 'Ativo',
                'is_novo' => true,
                'observacao' => 'Curso novo no PCA 2025',
            ],
            [
                'curso' => 'Técnico em Programação de Jogos Digitais',
                'eixo' => 'Tecnologia da informação - Games',
                'unidade' => 'Faculdade de Tecnologia e Inovação Senac-DF — Campus 712/912 Norte',
                'ano' => '2025',
                'ch' => '1000',
                'turmas' => '1',
                'codigo' => '2025.10.108 - Cancelada',
                'alunos' => '0',
                'instrutores' => null,
                'status' => 'Inativo',
                'is_novo' => false,
                'observacao' => 'Turma cancelada',
            ],
            [
                'curso' => 'Construção de Websites com PHP e MySQL',
                'eixo' => 'Tecnologia da Informação - Desenvolvimento',
                'unidade' => 'Taguatinga',
                'ano' => '2025',
                'ch' => '60',
                'turmas' => '1',
                'codigo' => '2025.08.123',
                'alunos' => '0',
                'instrutores' => 'Igor Medeiros Freitas',
                'status' => 'Ativo',
                'is_novo' => false,
                'observacao' => null,
            ],
            [
                'curso' => 'Aprendizagem Profissional de Qualificação em Serviços Administrativos',
                'eixo' => 'Gestão e Comércio',
                'unidade' => 'Gama',
                'ano' => '2025',
                'ch' => '1020',
                'turmas' => '6',
                'codigo' => '2025.10.113',
                'alunos' => '26',
                'instrutores' => 'Flávio Cavalcante Salomão',
                'status' => 'Ativo',
                'is_novo' => false,
                'observacao' => null,
            ],
            [
                'curso' => 'Educação Financeira',
                'eixo' => 'Educação',
                'unidade' => 'Ceilândia',
                'ano' => '2025',
                'ch' => '20',
                'turmas' => '6',
                'codigo' => '2025.07.158',
                'alunos' => '25',
                'instrutores' => 'Bianca Gabriel Fellet',
                'status' => 'Ativo',
                'is_novo' => false,
                'observacao' => null,
            ],
            [
                'curso' => 'Assistente de Marketing e Vendas',
                'eixo' => 'Vendas e Marketing',
                'unidade' => 'Sobradinho',
                'ano' => '2025',
                'ch' => '160',
                'turmas' => '3',
                'codigo' => '2025.08.192',
                'alunos' => '0',
                'instrutores' => 'Lucas Augusto Esmeraldo de Oliveira',
                'status' => 'Ativo',
                'is_novo' => false,
                'observacao' => null,
            ],
            [
                'curso' => 'Alongamento de Unhas',
                'eixo' => 'Beleza e cuidado pessoal',
                'unidade' => 'Santa Maria',
                'ano' => '2025',
                'ch' => '60',
                'turmas' => '1',
                'codigo' => '2025.09.71',
                'alunos' => '13',
                'instrutores' => 'Monica Rodrigues Da Costa Araujo',
                'status' => 'Ativo',
                'is_novo' => false,
                'observacao' => null,
            ],
            [
                'curso' => 'Técnico em Podologia',
                'eixo' => 'Estética e massoterapia',
                'unidade' => 'São Sebastião',
                'ano' => '2025',
                'ch' => '1200',
                'turmas' => '1',
                'codigo' => '2025.06.76',
                'alunos' => '32',
                'instrutores' => 'Jose Alves Pereira',
                'status' => 'Ativo',
                'is_novo' => false,
                'observacao' => null,
            ],
            [
                'curso' => 'Atualização em Procedimentos Técnicos aos Profissionais de Enfermagem',
                'eixo' => 'Enfermagem',
                'unidade' => 'Brazlândia',
                'ano' => '2025',
                'ch' => '200',
                'turmas' => '4',
                'codigo' => '2025.06.60',
                'alunos' => '30',
                'instrutores' => 'Paulo Philip de Abreu Gonzaga',
                'status' => 'Ativo',
                'is_novo' => false,
                'observacao' => null,
            ],
            [
                'curso' => 'Especialização em Enfermagem em Saúde Mental',
                'eixo' => 'Enfermagem',
                'unidade' => 'Faculdade de Tecnologia e Inovação Senac-DF — Campus 712/912 Norte',
                'ano' => '2025',
                'ch' => '300',
                'turmas' => '1',
                'codigo' => '2025.06.74',
                'alunos' => '13',
                'instrutores' => 'Francisco das Chagas Pontes',
                'status' => 'Ativo',
                'is_novo' => true,
                'observacao' => null,
            ],
            [
                'curso' => 'Técnico em Nutrição e Dietética',
                'eixo' => 'Nutrição',
                'unidade' => 'Faculdade de Tecnologia e Inovação Senac-DF — Campus 913 Sul',
                'ano' => '2025',
                'ch' => '1200',
                'turmas' => '2',
                'codigo' => '2025.08.164',
                'alunos' => '34',
                'instrutores' => 'Lewestter Melchior De Lima',
                'status' => 'Ativo',
                'is_novo' => false,
                'observacao' => null,
            ],
            [
                'curso' => 'Atendente de Farmácia',
                'eixo' => 'Farmácia',
                'unidade' => 'Taguatinga',
                'ano' => '2025',
                'ch' => '240',
                'turmas' => '1',
                'codigo' => '2025.08.112',
                'alunos' => '19',
                'instrutores' => 'Anna Maly de Leão e Neves Eduardo',
                'status' => 'Ativo',
                'is_novo' => false,
                'observacao' => null,
            ],
            [
                'curso' => 'Técnico em Segurança do Trabalho',
                'eixo' => 'Segurança e NRs',
                'unidade' => 'Gama',
                'ano' => '2025',
                'ch' => '1200',
                'turmas' => '5',
                'codigo' => '2025.06.71',
                'alunos' => '31',
                'instrutores' => 'Jessika Pereira Borba',
                'status' => 'Ativo',
                'is_novo' => false,
                'observacao' => null,
            ],
            [
                'curso' => 'Técnico em Radiologia',
                'eixo' => 'Radiologia',
                'unidade' => 'Faculdade de Tecnologia e Inovação Senac-DF — Campus Taguatinga',
                'ano' => '2025',
                'ch' => '1200',
                'turmas' => '1',
                'codigo' => '2025.10.111',
                'alunos' => '15',
                'instrutores' => 'Erika De Souza Figueiredo',
                'status' => 'Ativo',
                'is_novo' => false,
                'observacao' => null,
            ],
            [
                'curso' => 'Técnico em Saúde Bucal',
                'eixo' => 'Saúde Bucal',
                'unidade' => 'Santa Maria',
                'ano' => '2025',
                'ch' => '1200',
                'turmas' => '1',
                'codigo' => '2025.06.90',
                'alunos' => '18',
                'instrutores' => 'Carla Regina Souza',
                'status' => 'Ativo',
                'is_novo' => false,
                'observacao' => null,
            ],
            [
                'curso' => 'Açougueiro',
                'eixo' => 'Gastronomia',
                'unidade' => 'Faculdade de Tecnologia e Inovação Senac-DF — Campus 712/912 Norte',
                'ano' => '2024',
                'ch' => '160',
                'turmas' => '1',
                'codigo' => '2024.12.40',
                'alunos' => '10',
                'instrutores' => 'Hermesson Felipe Santos Da Silva',
                'status' => 'Ativo',
                'is_novo' => false,
                'observacao' => null,
            ],
            [
                'curso' => 'Barista',
                'eixo' => 'Bebidas',
                'unidade' => 'Taguatinga',
                'ano' => '2024',
                'ch' => '160',
                'turmas' => '1',
                'codigo' => '2024.26.10',
                'alunos' => '14',
                'instrutores' => 'Barbara Cristina Soares Carvalho',
                'status' => 'Ativo',
                'is_novo' => false,
                'observacao' => null,
            ],
            [
                'curso' => 'Administrador de Redes',
                'eixo' => 'Tecnologia da Informação - Suporte',
                'unidade' => 'São Sebastião',
                'ano' => '2024',
                'ch' => '200',
                'turmas' => '1',
                'codigo' => '2024.07.98',
                'alunos' => '12',
                'instrutores' => 'Moises Mendes de Andrade',
                'status' => 'Ativo',
                'is_novo' => false,
                'observacao' => null,
            ],
        ];

        foreach ($registros as $dados) {
            CursoPorEixo::updateOrCreate(
                [
                    'curso' => $dados['curso'],
                    'eixo' => $dados['eixo'],
                    'ano' => $dados['ano'],
                    'codigo' => $dados['codigo'],
                ],
                $this->comCiclo($dados)
            );
        }
    }
}
