<?php

/**
 * Catálogo de importações por módulo.
 * mode: single_sheet | multi_sheet
 */
return [
    'catalogo' => [
        'cursos' => [
            'key' => 'cursos',
            'label' => 'Cursos',
            'description' => 'Importa as abas de portfólio por eixo (título, CH, SIG, SEI, status…). Atualiza o ciclo selecionado sem apagar ciclos anteriores.',
            'ajuda' => 'Usa as abas de portfólio por eixo. A coluna Segmento é preservada. A aba Saúde vira Ambiente e Saúde. 60+ e Ensino Médio são programas, não eixos: cada linha precisa de um segmento (ou outro dado) que resolva um dos 5 eixos oficiais. A confirmação faz upsert no ciclo selecionado no seletor.',
            'model' => App\Models\Curso::class,
            'table' => 'cursos',
            'mode' => 'multi_sheet',
            'sheet_names' => [
                'Gastronomia e Turismo',
                'Saúde',
                'Ambiente e Saúde',
                'Gestão e Moda',
                'Tecnologia e Economia Criativa',
                'Beleza e Cuidado Pessoal',
                'Ensino Médio 2025',
                '60+',
            ],
            'header_markers' => ['titulo', 'ch', 'modalidade'],
            'required_any' => ['titulo'],
            'date_fields' => [],
            'columns' => [
                'status' => ['status sig', 'status'],
                'segmento' => ['segmento'],
                'eixo' => ['eixo'],
                'modalidade' => ['modalidade'],
                'titulo' => ['titulo - nome do curso', 'título - nome do curso', 'titulo', 'título'],
                'carga_horaria' => ['ch'],
                'codigo_dn' => ['cod. dn', 'cód. dn', 'codigo dn'],
                'codigo_sig' => ['cod. sig', 'cód. sig', 'codigo sig', 'sig'],
                'identificacao' => ['ident.', 'ident'],
                'tipo' => ['tipo'],
                'ultima_revisao' => ['ultima revisao', 'última revisão', 'ultima revisão'],
                'processo_sei' => ['processo sei'],
                'valores' => ['valores', 'valor'],
                'observacoes' => ['observacoes', 'observações', 'observacoes de conferencia', 'observações de conferência', 'observacoes / orientacoes', 'observações / orientações'],
                'unidade' => ['unidade que pode ser rodado', 'unidades que pode ser rodado'],
                'compativel_bolsa' => ['compativel com bolsa', 'compatível com bolsa'],
                'comercial' => ['comercial'],
                'pcn' => ['pcn'],
                'pcr' => ['pcr'],
            ],
            'preview_columns' => [
                ['key' => 'titulo', 'label' => 'Curso'],
                ['key' => 'eixo', 'label' => 'Eixo'],
                ['key' => 'segmento', 'label' => 'Segmento'],
                ['key' => 'modalidade', 'label' => 'Modalidade'],
                ['key' => 'status', 'label' => 'Status'],
                ['key' => 'codigo_sig', 'label' => 'SIG'],
                ['key' => 'processo_sei', 'label' => 'SEI'],
                ['key' => 'status_importacao', 'label' => 'Ação'],
            ],
            'db_fields' => [
                'titulo', 'eixo', 'segmento', 'programa', 'eixo_id', 'segmento_id', 'modalidade', 'carga_horaria', 'codigo_dn', 'codigo_sig',
                'identificacao', 'tipo', 'status', 'ultima_revisao', 'processo_sei',
                'valores', 'observacoes', 'unidade', 'compativel_bolsa', 'comercial', 'pcn', 'pcr',
            ],
            'defaults' => [
                'status' => 'ATIVO',
            ],
        ],

        'plano-de-metas' => [
            'key' => 'plano-de-metas',
            'label' => 'Plano de Metas',
            'description' => 'Importa a aba de Plano de Metas. Faz upsert no ciclo selecionado, sem apagar o ciclo anterior.',
            'ajuda' => 'Procura a aba “PLANO DE METAS 2025” (ou nome semelhante).',
            'model' => App\Models\PlanoDeMeta::class,
            'table' => 'plano_de_metas',
            'mode' => 'single_sheet',
            'sheet_names' => ['PLANO DE METAS 2025', 'Plano de Metas', 'PLANO DE METAS'],
            'header_markers' => ['segmento', 'tipo', 'status'],
            'required_any' => ['curso', 'numero_sei'],
            'date_fields' => [],
            'columns' => [
                'segmento' => ['segmento'],
                'curso' => ['curso'], // coluna sem nome: mapeada como segmento+1 no parser
                'tipo' => ['tipo'],
                'numero_sei' => ['numero sei', 'número sei'],
                'codigo_sig' => ['codigo sig', 'código sig'],
                'mes_entrega' => ['mes de entrega', 'mês de entrega'],
                'status' => ['status'],
                'origem' => ['origem'],
                'observacao' => ['observacao', 'observação'],
                'status_final' => ['status final'],
                'ano' => ['ano'],
            ],
            'preview_columns' => [
                ['key' => 'curso', 'label' => 'Curso'],
                ['key' => 'segmento', 'label' => 'Segmento'],
                ['key' => 'tipo', 'label' => 'Tipo'],
                ['key' => 'status', 'label' => 'Status'],
                ['key' => 'mes_entrega', 'label' => 'Mês'],
                ['key' => 'numero_sei', 'label' => 'SEI'],
            ],
            'unique_fields' => ['numero_sei', 'codigo_sig'],
            'db_fields' => [
                'segmento', 'curso', 'tipo', 'numero_sei', 'codigo_sig',
                'mes_entrega', 'status', 'origem', 'status_final', 'observacao', 'ano',
            ],
        ],

        'pcas' => [
            'key' => 'pcas',
            'label' => 'PCA',
            'description' => 'Importa a aba de propostas/valores do PCA. Faz upsert no ciclo selecionado, sem apagar o ciclo anterior.',
            'ajuda' => 'Prioriza a aba “PCA 2026 | Propostas” ou abas de Retificativos/Valores PCA.',
            'model' => App\Models\Pca::class,
            'table' => 'pcas',
            'mode' => 'single_sheet',
            'sheet_names' => [
                'PCA 2026 | Propostas',
                'PCA 2026 |Propostas',
                'Retificativos PCA_2025',
                'Retificativos PCA 2025',
                'Valores PCA 1°',
                'Valores PCA 2025 - Retificativo',
                'CURSOS NOVOS PCA_2025',
            ],
            'header_markers' => ['titulo', 'ch', 'status'],
            'required_any' => ['titulo', 'numero_sei', 'codigo_sig'],
            'date_fields' => [],
            'columns' => [
                'titulo' => ['titulo - nome do curso', 'títulos retificativos pca 2025 - cped', 'titulos', 'títulos', 'curso', 'titulo'],
                'eixo' => ['segmento', 'eixo'],
                'carga_horaria' => ['ch'],
                'codigo_sig' => ['cod. sig', 'cód. sig', 'codigo do plano de curso sig', 'sig', 'codigo sig'],
                'numero_sei' => ['processo sei', 'sei', 'n sei', 'numero sei', 'número sei'],
                'status' => ['status', 'status sig'],
                'precificacao' => ['precificacao', 'precificação', 'preco 2025', 'preço 2025', 'valor'],
                'valor_primeiro_modulo' => ['valor 1o modulo', 'valor 1º módulo'],
                'valor' => ['precificacao', 'precificação', 'preco 2025', 'preço 2025'],
                'parcelas_boleto' => ['n parcelas - boleto', 'parcelamento no boleto', 'boleto'],
                'valor_parcela_boleto' => ['valor parcela - boleto', 'valor no boleto'],
                'parcelas_cartao' => ['n parcelas - cartao', 'parcelamento no cartao', 'cartao de credito'],
                'valor_cartao' => ['valor - cartao', 'valor no cartao'],
                'parcela_desc_20' => ['parcela com desc de 20%', 'parcelas 20%'],
                'parcela_desc_15' => ['parcela com desc de 15%', 'parcela com 15%'],
                'unidade' => ['unidade'],
                'semestre' => ['semestre'],
                'ano' => ['ano'],
                'observacao' => ['observacao', 'observação', 'resolucao', 'resolução'],
            ],
            'preview_columns' => [
                ['key' => 'titulo', 'label' => 'Título'],
                ['key' => 'eixo', 'label' => 'Eixo'],
                ['key' => 'codigo_sig', 'label' => 'SIG'],
                ['key' => 'numero_sei', 'label' => 'SEI'],
                ['key' => 'status', 'label' => 'Status'],
                ['key' => 'unidade', 'label' => 'Unidade'],
                ['key' => 'precificacao', 'label' => 'Precificação'],
            ],
            'unique_fields' => ['numero_sei', 'codigo_sig'],
            'db_fields' => [
                'titulo', 'semestre', 'numero_sei', 'codigo_sig', 'eixo', 'unidade',
                'carga_horaria', 'precificacao', 'valor_primeiro_modulo', 'valor',
                'parcelas_boleto', 'valor_parcela_boleto', 'parcelas_cartao', 'valor_cartao',
                'parcela_desc_20', 'parcela_desc_15', 'status', 'observacao', 'ano',
            ],
        ],

        'eixos' => [
            'key' => 'eixos',
            'label' => 'Eixos',
            'description' => 'Importa a aba “Quantidade de cursos por eixo” como acompanhamento do ciclo. Vincula cursos já cadastrados; não cria curso novo.',
            'ajuda' => 'Usa a aba “Quantidade de cursos por eixo” (Código, Turmas e Alunos). Cada linha vira um acompanhamento do ciclo e tenta vincular a um curso já existente. Linhas sem correspondência ficam como pendência. A confirmação faz upsert e não apaga o ciclo anterior.',
            'model' => App\Models\CursoPorEixo::class,
            'table' => 'curso_por_eixos',
            'mode' => 'eixos_forward_fill',
            'sheet_names' => [
                'Quantidade de cursos por eixo',
                'Quantidade de Cursos por Eixo',
                'Quantidade de Cursos por Eixo ',
            ],
            'header_markers' => ['cursos', 'codigo', 'turmas', 'segmento'],
            'required_any' => ['curso', 'codigo'],
            'date_fields' => [],
            'columns' => [
                'eixo' => ['eixo'],
                'segmento' => ['segmento', 'eixo'],
                'curso' => ['cursos', 'curso'],
                'ch' => ['ch do curso', 'ch'],
                'turmas' => ['turmas (2o semestre)', 'turmas (2º semestre)', 'turmas'],
                'codigo' => ['codigo', 'código', 'cod.'],
                'alunos' => ['alunos (matriculas)', 'alunos'],
                'instrutores' => ['instrutores'],
            ],
            'preview_columns' => [
                ['key' => 'curso', 'label' => 'Curso'],
                ['key' => 'eixo', 'label' => 'Eixo'],
                ['key' => 'segmento', 'label' => 'Segmento'],
                ['key' => 'codigo', 'label' => 'Código'],
                ['key' => 'turmas', 'label' => 'Turmas'],
                ['key' => 'alunos', 'label' => 'Alunos'],
                ['key' => 'status_importacao', 'label' => 'Ação'],
            ],
            'db_fields' => ['curso', 'curso_id', 'eixo', 'segmento', 'programa', 'eixo_id', 'segmento_id', 'ch', 'turmas', 'codigo', 'alunos', 'instrutores'],
        ],

        'visitas-tecnicas' => [
            'key' => 'visitas-tecnicas',
            'label' => 'Visitas Técnicas',
            'description' => 'Importa a aba de processos de visitas técnicas. Substitui os registros atuais.',
            'ajuda' => 'Procura a aba “Processos de Visitas Técnicas”.',
            'model' => App\Models\VisitaTecnica::class,
            'table' => 'visita_tecnicas',
            'mode' => 'single_sheet',
            'sheet_names' => ['Processos de Visitas Técnicas', 'Visitas Técnicas', 'Visitas Tecnicas'],
            'header_markers' => ['processo sei', 'sei'],
            'required_any' => ['processo_sei', 'unidade'],
            'date_fields' => ['data_solicitacao', 'data_visita_prevista', 'prazo_limite'],
            'columns' => [
                'unidade' => ['relacao dos ceps', 'relação dos cep´s', 'relação dos ceps', 'unidade', 'cep'],
                'processo_sei' => ['processo sei', 'sei'],
                'observacao' => ['observacao', 'observação'],
                'eixo' => ['eixo'],
                'status' => ['status'],
                'responsavel' => ['responsavel', 'responsável'],
                'relatorio' => ['relatorio', 'relatório'],
                'data_solicitacao' => ['data solicitacao', 'data de solicitacao'],
                'prazo_limite' => ['prazo limite'],
            ],
            'preview_columns' => [
                ['key' => 'unidade', 'label' => 'Unidade'],
                ['key' => 'processo_sei', 'label' => 'SEI'],
                ['key' => 'observacao', 'label' => 'Observação'],
                ['key' => 'status', 'label' => 'Status'],
            ],
            'db_fields' => [
                'unidade', 'eixo', 'processo_sei', 'data_solicitacao', 'data_visita_prevista',
                'prazo_limite', 'status', 'responsavel', 'relatorio', 'observacao',
            ],
        ],

        'horas-pedagogicas' => [
            'key' => 'horas-pedagogicas',
            'label' => 'Horas Pedagógicas',
            'description' => 'Importa a aba de processos de horas pedagógicas. Substitui os registros atuais.',
            'ajuda' => 'Procura a aba “Processos Horas Pedagógicas”.',
            'model' => App\Models\HoraPedagogica::class,
            'table' => 'hora_pedagogicas',
            'mode' => 'single_sheet',
            'sheet_names' => [
                'Processos Horas Pedagógicas',
                'Processos Horas Pedagogicas',
                'Horas Pedagógicas',
            ],
            'header_markers' => ['processo sei', 'segmento'],
            'required_any' => ['processo_sei', 'eixo', 'segmento'],
            'date_fields' => [],
            'columns' => [
                'processo_sei' => ['processo sei', 'sei'],
                'segmento' => ['segmentos', 'segmento'],
                'eixo' => ['eixo', 'segmentos', 'segmento'],
                'pessoa' => ['pessoa'],
                'matricula' => ['matricula'],
                'ano' => ['ano'],
                'motivo' => ['motivo'],
                'status' => ['status'],
                'observacao' => ['observacao', 'observação'],
            ],
            'preview_columns' => [
                ['key' => 'processo_sei', 'label' => 'SEI'],
                ['key' => 'segmento', 'label' => 'Segmento'],
                ['key' => 'eixo', 'label' => 'Eixo'],
                ['key' => 'pessoa', 'label' => 'Pessoa'],
                ['key' => 'status', 'label' => 'Status'],
            ],
            'db_fields' => [
                'matricula', 'pessoa', 'segmento', 'eixo', 'processo_sei',
                'ano', 'motivo', 'status', 'ativo', 'observacao',
            ],
        ],

        'acoes-extensivas' => [
            'key' => 'acoes-extensivas',
            'label' => 'Ações Extensivas',
            'description' => 'Importa a aba “Ações extensivas”. Substitui todos os registros do módulo.',
            'ajuda' => 'Usa apenas a aba “Ações extensivas” da planilha enviada.',
            'model' => App\Models\AcaoExtensiva::class,
            'table' => 'acao_extensivas',
            'mode' => 'single_sheet',
            'sheet_names' => ['Ações extensivas', 'Acoes extensivas', 'Ações Extensivas'],
            'header_markers' => ['priorizacao', 'assunto'],
            'required_any' => ['assunto', 'numero_processo_sei'],
            'date_fields' => ['ultima_atualizacao'],
            'columns' => [
                'priorizacao' => ['priorização', 'priorizacao'],
                'atribuido' => ['atribuído', 'atribuido'],
                'eixo' => ['eixo'],
                'numero_processo_sei' => ['número do processo sei', 'numero do processo sei', 'número do processo', 'numero do processo'],
                'tipo' => ['tipo'],
                'assunto' => ['assunto'],
                'objetivo' => ['objetivo'],
                'status' => ['status'],
                'ultima_atualizacao' => ['última atualização', 'ultima atualizacao', 'última atualizacao', 'ultima atualização'],
            ],
            'preview_columns' => [
                ['key' => 'priorizacao', 'label' => 'Priorização'],
                ['key' => 'atribuido', 'label' => 'Atribuído'],
                ['key' => 'eixo', 'label' => 'Eixo'],
                ['key' => 'numero_processo_sei', 'label' => 'SEI'],
                ['key' => 'tipo', 'label' => 'Tipo'],
                ['key' => 'assunto', 'label' => 'Assunto'],
                ['key' => 'status', 'label' => 'Status'],
                ['key' => 'ultima_atualizacao', 'label' => 'Atualização'],
            ],
            'db_fields' => [
                'priorizacao', 'atribuido', 'eixo', 'numero_processo_sei', 'tipo',
                'assunto', 'objetivo', 'status', 'ultima_atualizacao',
            ],
        ],

        'eventos' => [
            'key' => 'eventos',
            'label' => 'Eventos',
            'description' => 'Importa a aba “Eventos” com colunas padronizadas. Substitui os registros atuais.',
            'ajuda' => 'A planilha deve ter uma aba chamada “Eventos” com colunas como Nome, Data, Unidade, Eixo, Status.',
            'model' => App\Models\Evento::class,
            'table' => 'eventos',
            'mode' => 'single_sheet',
            'sheet_names' => ['Eventos', 'EVENTOS'],
            'header_markers' => ['nome', 'data', 'unidade'],
            'required_any' => ['nome'],
            'date_fields' => ['data'],
            'columns' => [
                'nome' => ['nome', 'evento', 'titulo', 'título'],
                'ano' => ['ano'],
                'data' => ['data'],
                'unidade' => ['unidade'],
                'eixo' => ['eixo', 'segmento'],
                'quantidade_pessoas' => ['quantidade pessoas', 'pessoas', 'qtd pessoas'],
                'equipe' => ['equipe'],
                'possui_acao_extensiva' => ['possui acao extensiva', 'acao extensiva'],
                'acao_vinculada' => ['acao vinculada', 'ação vinculada'],
                'status' => ['status'],
                'observacao' => ['observacao', 'observação'],
            ],
            'preview_columns' => [
                ['key' => 'nome', 'label' => 'Evento'],
                ['key' => 'data', 'label' => 'Data'],
                ['key' => 'unidade', 'label' => 'Unidade'],
                ['key' => 'eixo', 'label' => 'Eixo'],
                ['key' => 'status', 'label' => 'Status'],
            ],
            'db_fields' => [
                'nome', 'ano', 'data', 'unidade', 'eixo', 'quantidade_pessoas',
                'equipe', 'possui_acao_extensiva', 'acao_vinculada', 'status', 'observacao',
            ],
        ],
    ],
];
