export const UNIDADES = [
  'Faculdade de Tecnologia e Inovação Senac-DF — Campus 712/912 Norte',
  'Faculdade de Tecnologia e Inovação Senac-DF — Campus 913 Sul',
  'Faculdade de Tecnologia e Inovação Senac-DF — Campus Taguatinga',
  'Senac Brazlândia',
  'Polo de Educação Profissional Senac Israel Pinheiro — Candangolândia',
  'Senac Pátio Brasil Shopping',
  'Polo de Educação Profissional Senac — Planaltina',
  'Polo de Educação Profissional Senac — Recanto das Emas',
  'Senac Santa Maria',
  'Senac São Sebastião',
  'Centro de Educação Profissional Ennius Marcus de Moraes Muniz',
  'Centro de Educação Profissional Sobradinho',
  'Centro de Educação Profissional Joaquim Loiola — Gama',
  'Centro de Educação Profissional Talal Abu-Allan — Ceilândia',
  'Centro de Educação Profissional Miguel Setembrino — Setor Comercial Sul',
];
